spring.application.name=apigateway
server.port=8083
# Register with Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# Enable automatic route discovery
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# Addition Service
spring.cloud.gateway.server.webflux.routes[0].id=addition-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ADDITIONSERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/addition/**
